CREATE DATABASE OPTUSempresa;
GO

USE OPTUSempresa;
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(20)
);
GO

 CREATE TABLE ARTISTA(
 idArtista SMALLINT PRIMARY KEY IDENTITY (1,1),
 idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA (idEmpresa),
 nomeArtista VARCHAR(20) NOT NULL
 );
 GO

 CREATE TABLE ALBUM(
 idAlbum SMALLINT PRIMARY KEY IDENTITY (1,1),
 idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
 nomeAlbum VARCHAR(20) NOT NULL
 );
 GO

 CREATE TABLE ESTILO(
 idEstilo SMALLINT PRIMARY KEY IDENTITY (1,1),
 idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
 nomeEstilo VARCHAR(20) NOT NULL
 );
 GO

 CREATE TABLE PLATAFORMA(
 idPlataforma SMALLINT PRIMARY KEY IDENTITY (1,1),
 idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
 descricao VARCHAR(30) NOT NULL
 );
 GO

  CREATE TABLE Usuario(
 idUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
 idPlataforma  SMALLINT FOREIGN KEY REFERENCES PLATAFORMA(idPlataforma),
 nomeUsuario VARCHAR(30) NOT NULL, 
 emailUsuario VARCHAR(256) NOT NULL UNIQUE,
 senhaUsuario VARCHAR (30) NOT NULL
 );
 GO


