CREATE DATABASE VETERINARIA;
GO

USE VETERINARIA;
GO

CREATE TABLE CLINICA(
idClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
enderecoClinica VARCHAR(70), 
nomeClinica VARCHAR(20)
);
GO


 CREATE TABLE VETERINARIO(
 idVeterinario SMALLINT PRIMARY KEY IDENTITY (1,1),
 idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA (idClinica),
 nomeVeterinario VARCHAR(20) NOT NULL
 );
 GO


 CREATE TABLE ATENDIMENTO(
 idAtendimento SMALLINT PRIMARY KEY IDENTITY (1,1),
 idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO (idVeterinario),
 dataAtendimento VARCHAR(9) NOT NULL
 );
 GO


 CREATE TABLE PET(
 idPet SMALLINT PRIMARY KEY IDENTITY (1,1),
 idAtendimento SMALLINT FOREIGN KEY REFERENCES ATENDIMENTO (idAtendimento),
 nascimentoPet VARCHAR(9) NOT NULL,
 nomePet VARCHAR(20) NOT NULL
 );
 GO


 CREATE TABLE RAÇA(
 idRaça SMALLINT PRIMARY KEY IDENTITY (1,1),
 idPet SMALLINT FOREIGN KEY REFERENCES PET (idPet),
 nomeRaça VARCHAR(16) NOT NULL
 );
 GO

 CREATE TABLE TIPO(
 idTipo SMALLINT PRIMARY KEY IDENTITY (1,1),
 idRaça SMALLINT FOREIGN KEY REFERENCES RAÇA (idRaça),
 nomeTipo VARCHAR(15) NOT NULL
 );
 GO

 CREATE TABLE Dono(
 idDono SMALLINT PRIMARY KEY IDENTITY (1,1),
 idPet SMALLINT FOREIGN KEY REFERENCES PET (idPet),
 nomeDono VARCHAR(20) NOT NULL
 );
 GO





