CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA (
idEmpresa TINYINT PRIMARY KEY IDENTITY (1,1),
nomeEmpresa VARCHAR (30) NOT NULL
);
GO

 CREATE TABLE VEICULO(
 idVeiculo SMALLINT PRIMARY KEY IDENTITY (1,1),
 idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA (idEmpresa),
 placaVeiculo CHAR(7) NOT NULL
 );
GO

 CREATE TABLE MODELO(
 idModelo SMALLINT PRIMARY KEY IDENTITY (1,1),
 idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
 nomeModelo VARCHAR(25) NOT NULL
 );
 GO

 CREATE TABLE MARCA(
 idMarca SMALLINT PRIMARY KEY IDENTITY (1,1),
 idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
 nomeMarca VARCHAR(25) NOT NULL
 );
GO

 CREATE TABLE ALUGUEL(
 idAluguel SMALLINT PRIMARY KEY IDENTITY (1,1),
 idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
 dataAluguel VARCHAR(9) NOT NULL
 );
GO

  CREATE TABLE CLIENTE(
 idCliente SMALLINT PRIMARY KEY IDENTITY (1,1),
 idAluguel SMALLINT FOREIGN KEY REFERENCES ALUGUEL(idAluguel),
 nomeCliente VARCHAR(20) NOT NULL,
 cpfCliente CHAR(11) NOT NULL
 );
 GO
 






